### ISSUE TITLE
http pool stuck

### ISSUE THREAD

**Issue by ice-tea** [UnboundID/scim#7] opened 2016-07-26 00:13 UTC
Description:
When send multiple requests on single SCIMEndpoint, the third request starts to be stuck(await forever).

Solution:
In "scim-sdk/src/main/java/com/unboundid/scim/sdk/SCIMEndpoint.java"
It seems should close every response. (right now just close entity).

**Comment by richardcardona** [comment] 2016-07-29 15:21
SCIMEndpoint can only call entity.close() since ClientResponse does not expose a close method or a getter for the Response object.
 
This is the javadoc from the close method of javax.ws.rs.core.Response:
> **public abstract void close()**
> Close the underlying message entity input stream (if available and open) as well as releases any other resources associated with the response (e.g. buffered message entity data).
> This operation is idempotent, i.e. it can be invoked multiple times with the same effect which also means that calling the close() method on an already closed message instance is legal and has no further effect.
> 
> The close() method should be invoked on all instances that contain an un-consumed entity input stream to ensure the resources associated with the instance are properly cleaned-up and prevent potential memory leaks. This is typical for client-side scenarios where application layer code processes only the response headers and ignores the response entity.
> 
> Any attempts to manipulate (read, get, buffer) a message entity on a closed response will result in an IllegalStateException being thrown.

From above, closing the entity is equivalent to Response.close() if the entity is always consumed. For SCIM resources, there are no other close-able resources associated with the response.

Does your http server access log show that your third SCIM request was processed? For debugging purposes, what happens if you create a new SCIMEndpoint for every request?

**Comment by ice-tea** [comment] 2016-07-29 19:15
Here is the debugging messages when I call query function three times on a certain SCIMEndpoint:

The HTTP log shows the third request is send:

> Jul 29, 2016 12:05:11 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 3 * Sending client request on thread main
3 > GET https://xxxxx-dev-ed.my.salesforce.com/services/scim/v1/Users
3 > Accept: application/json

The Dump Thread message from IntelliJ:

> "Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x0000000017807800 nid=0x1260 in Object.wait() [0x0000000018a4f000]
   java.lang.Thread.State: WAITING (on object monitor)
  at java.lang.Object.wait(Native Method)
  - waiting on <0x00000000d8008a90> (a java.lang.ref.Reference$Lock)
  at java.lang.Object.wait(Object.java:502)
  at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
  - locked <0x00000000d8008a90> (a java.lang.ref.Reference$Lock)
  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

> "main" #1 prio=5 os_prio=0 tid=0x000000000220a000 nid=0x1034 waiting on condition [0x000000000271d000]
   java.lang.Thread.State: WAITING (parking)
  at sun.misc.Unsafe.park(Native Method)
  - parking to wait for  <0x00000000d7db8170> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
  at org.apache.http.pool.PoolEntryFuture.await(PoolEntryFuture.java:138)
  at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:306)
  at org.apache.http.pool.AbstractConnPool.access$000(AbstractConnPool.java:64)
  at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:192)
  at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:185)
  at org.apache.http.pool.PoolEntryFuture.get(PoolEntryFuture.java:107)
  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:276)
  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:263)
  at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
  at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
  at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
  at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
  at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
  at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
  at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:671)
  at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:668)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
  at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:668)
  at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:402)
  at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:302)
  at org.apache.wink.client.Resource.get(Resource.java:183)
  at com.unboundid.scim.sdk.SCIMEndpoint.query(SCIMEndpoint.java:352)
  at com.unboundid.scim.sdk.SCIMEndpoint.query(SCIMEndpoint.java:276)
  at com.unboundid.scim.sdk.SCIMEndpoint.query(SCIMEndpoint.java:254)
  at com.amazonaws.scim.Demo2.main(Demo2.java:55)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

The code is like:

`
        
        // Core user resource CRUD operation example
        final SCIMService scimService = new SCIMService(uri, new OAuthToken("xxx"));
        scimService.setAcceptType(MediaType.APPLICATION_JSON_TYPE);
        final SCIMEndpoint<UserResource> userEndpoint = scimService.getUserEndpoint();
        for (int i = 1; i < 5; ++i) {
            Resources<UserResource> users = userEndpoint.query(null);
            String userId;
            for (UserResource user : users) {
                userId = user.getId();
                System.out.println(userId);
            }
            System.out.println("------------");
        }`

**Comment by ice-tea** [comment] 2016-07-29 19:22
"if I create a new SCIMEndpoint for every request", this error disappears.
So if it's a convention that only send a single request on certain EndPoint? 
     Which add burden on users and seems waste of resources.
Or, did I fail to use this library properly? like entity is not consumed normally?

**Comment by ice-tea** [comment] 2016-07-29 21:35
Maybe the updated org.apache.wink.client (v1.4) deals it properly.

However, as "org\apache\wink\client" is already a part of the source code(like from v1.2), by adding close() function in ClientResponse.java (manually call close function on the private Response member), this problem can be solved.This is the best I can do.

Looking forward a more reasonable solution here.

**Comment by richardcardona** [comment] 2016-08-01 01:33
You should not have to create a new SCIMEndpoint per request. This is a bug. After getting an access token for our Salesforce domain, I have confirmed a hang in exactly the same way you are seeing. I opened an internal JIRA issue on the problem. Unfortunately I cannot provide an estimate of when we can commit a public fix.

Also I confirmed that adding a close() method to the ClientResponse object (which calls close on the private Response member) and changing SCIMEndpoint to close the ClientResource instead of the response entity avoids the hang. While this is a workaround, it does not necessarily mean we will fix the issue this way.

Thank you for reporting the problem.

**Comment by ice-tea** [comment] 2016-08-01 18:20
Tanks for your reply. Actually UnboundID is the most powerful SCIM client I ever tried.
 It's my pleasure to be helpful.

**Comment by bertold** [comment] 2016-08-05 01:27
This problem has been resolved in the 1.8.13 release. Thanks again for reporting this issue.

**Closed by bertold** 2016-08-05 01:27 UTC
